/* UI is deliberately separate from game rules, so saves and offline logic stay testable. */
'use strict';
(() => {
const G=CatGame, KEY='cat-courtyard-v1';
const $=s=>document.querySelector(s);
const escapeHtml=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state=null,tab='cats',toastTimer,storageOK=true;
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3500);}
function save(){if(!state)return;try{localStorage.setItem(KEY,JSON.stringify(state));}catch{storageOK=false;toast('浏览器暂时无法保存，建议导出一份存档。');}}
function catSVG(c){const coat=G.coats.find(x=>x.id===c.coat)||G.coats[0],color=coat.color,dark=coat.dark;
 const long=c.coat==='white';
 const pattern=c.coat==='calico'||c.coat==='tuxedo'||c.pattern==='patch'?`<path d="M47 50 Q50 26 71 38 L77 59 Q60 69 47 50" fill="${dark}"/><ellipse cx="91" cy="88" rx="11" ry="18" fill="${c.coat==='calico'?'#65605a':dark}"/>`:c.pattern==='stripe'?`<g stroke="${dark}" stroke-width="4" stroke-linecap="round"><path d="M68 38l3 10m9-11v9m10-7l-3 9M48 66l10 3m45-4l-10 4M58 88l7 3m36-4l-7 4"/></g>`:'';
 return `<svg viewBox="0 0 150 130" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><ellipse cx="77" cy="117" rx="40" ry="5" fill="#8a8761" opacity=".12"/><path d="M105 101Q135 102 125 77" fill="none" stroke="${color}" stroke-width="13" stroke-linecap="round"/><ellipse cx="77" cy="90" rx="30" ry="28" fill="${color}"/>${long?`<path d="M51 77l-10 11 10 2-8 10 15-2m43-20l11 12-10 1 10 10-17-4" fill="${color}"/>`:''}<path d="M46 55L45 20Q57 20 66 37L86 37Q95 19 106 22L105 56" fill="${color}" stroke="${dark}" stroke-width="1.2"/><path d="M49 29l2 17 10-7m37-9l-7 11 10 7" fill="#dbaaaa"/><ellipse cx="77" cy="58" rx="32" ry="26" fill="${color}"/>${pattern}<ellipse cx="76" cy="69" rx="15" ry="10" fill="#fff9ec" opacity=".72"/><g fill="${c.coat==='black'?'#d6ce98':'#53574a'}"><ellipse cx="64" cy="59" rx="3" ry="4"/><ellipse cx="90" cy="59" rx="3" ry="4"/></g><path d="M73 66l7 0-3.5 4z" fill="#b78882"/><path d="M77 70q-4 5-7 0m7 0q4 5 7 0" stroke="#827566" fill="none" stroke-width="1.4" stroke-linecap="round"/><g stroke="#8b8173" stroke-width="1" opacity=".6"><path d="M54 68l-14-2m14 6l-13 3m58-7l13-2m-13 7l13 3"/></g><ellipse cx="63" cy="112" rx="12" ry="7" fill="${color}"/><ellipse cx="91" cy="112" rx="12" ry="7" fill="${color}"/>${c.accessory==='scarf'?'<path d="M53 80Q77 92 101 80L100 87Q77 99 53 87Z" fill="#9aaf87"/><path d="M91 87l8 18-13-1-1-17" fill="#9aaf87"/>':c.accessory==='bow'?'<path d="M73 84l-13-8v17l13-7m7-2l13-8v17l-13-7" fill="#c08c84"/><circle cx="77" cy="85" r="4" fill="#aa776f"/>':''}</svg>`;
}
function modal(html,closable=true){$('#modal-content').innerHTML=html;const close=$('#close-modal');if(close)close.onclick=()=>$('#modal').close();$('#modal').onkeydown=e=>{if(e.key==='Escape'&&!closable)e.preventDefault();};if(!$('#modal').open)$('#modal').showModal();}
function top(title,close=true){return `<div class="modal-top"><h2>${title}</h2>${close?'<button id="close-modal" class="close" aria-label="关闭">×</button>':''}</div>`;}
function onboarding(){let opts={name:'小橘',coat:'orange',pattern:'stripe',accessory:'none'};
 modal(`${top('先认识你的第一只小猫',false)}<p class="modal-sub">它将和你一起，把这座小院变成家。</p><div id="preview" class="preview-cat"></div><label class="field" for="cat-name">给它起个名字</label><input id="cat-name" class="name-input" maxlength="16" value="小橘" placeholder="例如：团子、芝麻"><label class="field">喜欢什么毛色？</label><div class="swatches">${G.coats.map(c=>`<button class="swatch ${c.id==='orange'?'selected':''}" data-coat="${c.id}" style="background:${c.color}" aria-label="${c.name}" title="${c.name}"></button>`).join('')}</div><label class="field">小小的花纹</label><div class="choices" id="patterns"><button data-pattern="stripe" class="selected">小条纹</button><button data-pattern="solid">纯色</button><button data-pattern="patch">小斑块</button></div><label class="field">添一点可爱</label><div class="choices" id="accessories"><button data-accessory="none" class="selected">原本的样子</button><button data-accessory="scarf">绿围巾</button><button data-accessory="bow">小蝴蝶结</button></div><button id="start" class="primary">一起回家吧 ♡</button>`,false);
 const preview=()=>{$('#preview').innerHTML=catSVG(opts);};preview();
 document.querySelectorAll('[data-coat]').forEach(b=>b.onclick=()=>{opts.coat=b.dataset.coat;document.querySelectorAll('[data-coat]').forEach(x=>x.classList.toggle('selected',x===b));preview();});
 for(const key of ['pattern','accessory'])document.querySelectorAll(`[data-${key}]`).forEach(b=>b.onclick=()=>{opts[key]=b.dataset[key];document.querySelectorAll(`[data-${key}]`).forEach(x=>x.classList.toggle('selected',x===b));preview();});
 $('#start').onclick=()=>{opts.name=G.safeName($('#cat-name').value)||'小橘';state=G.newGame(opts);G.addVisitor(state,Date.now());save();$('#modal').close();render();toast('欢迎回家。门口已经有一位好奇的新朋友！');};
}
function render(){if(!state)return;$('#coins').textContent=Math.floor(state.coins);$('#resident-count').textContent=state.cats.filter(c=>c.status!=='visitor').length;$('#visitor-count').textContent=state.cats.filter(c=>c.status==='visitor').length;$('#collect').textContent=state.gifts?`🎁 小礼物 +${state.gifts}`:'🎁 小猫的礼物';$('#collect').disabled=!state.gifts;CourtyardScene.setState(state);renderPanel();}
function card(c){return `<button class="cat-card" data-cat="${escapeHtml(c.id)}"><span class="cat-avatar">${catSVG(c)}</span><span style="flex:1"><b>${escapeHtml(c.name)}</b><span class="badge">${c.status==='visitor'?'来访中':c.status==='starter'?'主人猫':'已定居'}</span><span class="cat-meta">${escapeHtml(c.breed)} · ${escapeHtml(c.personality)}</span><span class="bar"><i style="width:${c.status==='visitor'?c.trust:Math.min(100,20+c.affection)}%"></i></span><span class="tiny">${c.status==='visitor'?`信任 ${c.trust}/100`:`亲密度 ${c.affection} · 今天也喜欢你`}</span></span></button>`;}
function renderPanel(){document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));const panel=$('#panel');
 if(tab==='cats'){const residents=state.cats.filter(c=>c.status!=='visitor'),visitors=state.cats.filter(c=>c.status==='visitor');panel.innerHTML=`<div class="panel-title"><h2>小院里的小家人</h2><small>${residents.length} 只猫咪</small></div><p class="subtext">每一只小猫，都值得被好好记住。</p>${residents.map(card).join('')}<div class="section-label">门口的新朋友</div>${visitors.length?visitors.map(card).join(''):'<div class="empty"><span>🐾</span>门口暂时很安静。<br>布置好小院，让缘分慢慢来。<br>新朋友大约每半小时有机会来访。</div>'}`;}
 else if(tab==='shop'){panel.innerHTML=`<div class="panel-title"><h2>给小院添点美好</h2><small>${state.placed.length} 件已摆放</small></div><p class="subtext">不同小物件，会吸引不同性格的小猫。</p><div class="shop-grid">${G.items.map(i=>`<div class="shop-item"><span>${i.emoji}</span><b>${i.name}</b><p>${i.desc}</p><button data-buy="${i.id}" ${!state.owned.includes(i.id)&&state.coins<i.price?'disabled':''}>${state.owned.includes(i.id)?state.placed.includes(i.id)?'已摆放 · 收起':'摆进小院':`✧ ${i.price} 解锁`}</button></div>`).join('')}</div>`;
 document.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>{const id=b.dataset.buy;if(state.owned.includes(id)){state.placed=state.placed.includes(id)?state.placed.filter(x=>x!==id):[...state.placed,id];}else if(G.buy(state,id))toast('小院又多了一点可爱。');save();render();});}
 else panel.innerHTML=`<div class="panel-title"><h2>有猫的小日子</h2><small>${state.memories.length} 个瞬间</small></div><p class="subtext">那些小小的瞬间，也值得被珍藏。</p>${state.memories.map(m=>`<div class="memory"><time>${new Date(m.at).toLocaleString('zh-CN',{month:'long',day:'numeric',hour:'2-digit',minute:'2-digit'})}</time><p>${escapeHtml(m.text)}</p></div>`).join('')}`;
 bindCats();}
function bindCats(){document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>detail(b.dataset.cat));}
function detail(id){const c=state.cats.find(x=>x.id===id);if(!c)return;modal(`${top('和小猫待一会')}<div class="cat-detail"><div class="preview-cat">${catSVG(c)}</div><h3>${escapeHtml(c.name)}</h3><p>${escapeHtml(c.breed)} · ${escapeHtml(c.personality)} · 喜欢${({food:'吃饭',box:'纸箱',warm:'暖暖的地方',plant:'花草',play:'小玩具',climb:'爬高高'})[c.favorite]||'晒太阳'}</p><div class="bar"><i style="width:${c.status==='visitor'?c.trust:Math.min(100,20+c.affection)}%"></i></div><p>${c.status==='visitor'?`信任 ${c.trust}/100 · 多陪伴几次，它就愿意留下。`:`亲密度 ${c.affection} · 院子永远是它的家。`}</p></div><div class="action-row"><button class="secondary" id="pet">♡ 轻轻摸摸</button><button class="secondary" id="feed">🥣 添一碗饭</button></div>${c.status==='visitor'?`<button id="adopt" class="primary" ${c.trust<100?'disabled':''}>${c.trust<100?'再熟悉一点，就能邀请它留下':'邀请它成为小家人'}</button>`:'<button id="rename" class="primary">给它换个名字</button>'}<p class="tiny" style="text-align:center">陪伴每分钟记一次。随时回来，不用着急。</p>`);
 for(const a of ['pet','feed'])$('#'+a).onclick=()=>{const r=G.interact(state,id,a);save();render();if(r.ok){CourtyardScene.react(id,a);$('#modal').close();if($('#collection').open)$('#collection').close();}toast(r.text);};
 if($('#adopt'))$('#adopt').onclick=()=>nameDialog(c,true);if($('#rename'))$('#rename').onclick=()=>nameDialog(c,false);}
function nameDialog(c,adopting){modal(`${top(adopting?'从今天起，这里就是家':'一个属于它的名字')}<div class="preview-cat">${catSVG(c)}</div><label class="field" for="new-name">你想叫它什么？</label><input id="new-name" class="name-input" maxlength="16" value="${escapeHtml(c.name)}"><button id="confirm-name" class="primary">${adopting?'欢迎回家 ♡':'记住这个名字'}</button>`);$('#confirm-name').onclick=()=>{const name=G.safeName($('#new-name').value)||c.name;if(adopting)G.adopt(state,c.id,name);else{c.name=name;G.memory(state,`给小猫取了一个新名字：「${name}」。`);}save();render();$('#modal').close();toast(adopting?`${name}留下来了，今后一起过日子。`:'名字已记在猫咪的小档案里。');};}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{if(!state)return;tab=b.dataset.tab;$('#collection-title').textContent=({cats:'小家人',shop:'布置你的家',memories:'有猫的回忆'})[tab];renderPanel();if(!$('#collection').open)$('#collection').showModal();});
$('#close-collection').onclick=()=>$('#collection').close();
$('#call-cats').onclick=()=>{CourtyardScene.call();toast('轻轻摇摇零食袋，小猫朝你走来了。');};
document.addEventListener('catselect',e=>detail(e.detail));
$('#collect').onclick=()=>{if(!state?.gifts)return;const n=state.gifts;state.coins+=n;state.gifts=0;G.memory(state,`猫咪们留下的小礼物，带来了 ${n} 枚猫爪印。`);save();render();toast(`收下小小心意，猫爪印 +${n}`);};
$('#save-info').onclick=()=>{modal(`${top('小院设置')}<div class="help"><p>点击猫咪可喂食、抚摸、命名。点击房门或底部地图，可以探索小院、卧室、厨房和猫窝房。来访猫在小院等你，定居猫会陪你进屋。</p><p>每分钟记一次陪伴。离线每半小时积累 3 枚猫爪印，最多结算 12 小时。</p><p>进度自动保存在当前浏览器。换设备或清除数据前，请导出存档。</p></div><div class="action-row"><button id="settings-export" class="secondary">导出存档</button><button id="settings-import" class="secondary">导入存档</button></div>`);$('#settings-export').onclick=()=>$('#export-save').click();$('#settings-import').onclick=()=>$('#import-save').click();};
$('#export-save').onclick=()=>{if(!state)return;const url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='猫咪小院-存档.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('存档已导出，请好好保管。');};
$('#import-save').onclick=()=>$('#import-file').click();$('#import-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>1000000)throw Error('存档过大');const imported=G.normalize(JSON.parse(await file.text()));modal(`${top('接回另一座小院')}<p class="help">这份存档里有 ${imported.cats.length} 只猫咪。导入会替换当前小院，建议先导出当前进度。</p><button id="confirm-import" class="primary">使用这份存档</button>`);$('#confirm-import').onclick=()=>{state=imported;G.settle(state);save();render();$('#modal').close();toast('小猫们都回来了。');};}catch{toast('这份存档无法读取，请选择导出的 JSON 存档。');}e.target.value='';};
function checkOffline(){if(!state)return;const result=G.settle(state);save();render();if(result.elapsed>30*60000&&(result.gifts||result.visits))modal(`${top('欢迎回来，猫咪想你了')}<div class="preview-cat">${catSVG(state.cats[0])}</div><p class="help">你不在的时候，小院也过得很好。<br>猫咪留下了 <b>${result.gifts} 枚猫爪印</b>${result.visits?'，还有一位新朋友在门口等你':''}。</p><button id="back-yard" class="primary">看看小院 ♡</button>`),$('#back-yard').onclick=()=>$('#modal').close();}
document.addEventListener('visibilitychange',()=>{if(document.hidden){if(state){state.lastSeen=Date.now();save();}}else checkOffline();});
window.addEventListener('pagehide',()=>{if(state){state.lastSeen=Date.now();save();}});
setInterval(()=>{if(state&&!document.hidden){const r=G.settle(state);save();if(r.visits){render();toast('门口有一位新朋友，去打声招呼吧。');}}},30000);
try{const raw=localStorage.getItem(KEY);if(raw)state=G.normalize(JSON.parse(raw));}catch{toast('旧存档暂时无法读取，可以导入备份或重新领养。');}
if(state)checkOffline();else onboarding();
})();

