/* UI is deliberately separate from game rules, so saves and offline logic stay testable. */
'use strict';
(() => {
const G=CatGame, KEY='cat-courtyard-v1';
const $=s=>document.querySelector(s);
const escapeHtml=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state=null,tab='cats',toastTimer,storageOK=true,detailId=null;
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3500);}
function save(){if(!state)return;try{localStorage.setItem(KEY,JSON.stringify(state));}catch{storageOK=false;toast('浏览器暂时无法保存，建议导出一份存档。');}}
function catSVG(c){const portrait=window.CourtyardScene?.portrait?.(c);return portrait?`<img class="cat-portrait" data-portrait="${escapeHtml(c.id||'preview')}" src="${portrait}" alt="${escapeHtml(G.visitorDescription(c))}">`:'<span class="portrait-loading" role="status">小猫正在走过来…</span>';}
function modal(html,closable=true){detailId=null;$('#modal-content').innerHTML=html;const close=$('#close-modal');if(close)close.onclick=()=>$('#modal').close();$('#modal').onkeydown=e=>{if(e.key==='Escape'&&!closable)e.preventDefault();};if(!$('#modal').open)$('#modal').showModal();}
function top(title,close=true){return `<div class="modal-top"><h2>${title}</h2>${close?'<button id="close-modal" class="close" aria-label="关闭">×</button>':''}</div>`;}
function onboarding(){let opts={name:'小橘',coat:'orange',breedId:'domestic',pattern:'stripe',accessory:'none'};
 modal(`${top('家 · 先认识你的第一只小猫',false)}<p class="modal-sub">它将和你一起，把这座小院变成家。</p><div id="preview" class="preview-cat"></div><label class="field" for="cat-name">给它起个名字</label><input id="cat-name" class="name-input" maxlength="16" value="小橘" placeholder="例如：团子、芝麻"><label class="field" for="cat-breed">选择猫咪品种</label><select id="cat-breed" class="name-input">${G.breeds.map(b=>`<option value="${b.id}">${b.name}</option>`).join('')}</select><label class="field">喜欢什么毛色？</label><div class="swatches">${G.coats.map(c=>`<button class="swatch ${c.id==='orange'?'selected':''}" data-coat="${c.id}" style="background:${c.color}" aria-label="${c.name}" title="${c.name}"></button>`).join('')}</div><p id="appearance-label" class="tiny"></p><label class="field">小小的花纹</label><div class="choices" id="patterns">${G.patterns.map(p=>`<button data-pattern="${p.id}" class="${p.id==='stripe'?'selected':''}">${p.name}</button>`).join('')}</div><label class="field">添一点可爱</label><div class="choices" id="accessories"><button data-accessory="none" class="selected">原本的样子</button><button data-accessory="scarf">绿围巾</button><button data-accessory="bow">小蝴蝶结</button></div><button id="start" class="primary">一起回家吧 ♡</button>`,false);
 const preview=()=>{opts.pattern=G.resolvePattern(opts.coat,opts.pattern);$('#preview').innerHTML=catSVG(opts,true);$('#appearance-label').textContent=`${G.breedFor(opts).name} · ${G.appearanceLabel(opts)}${['calico','tuxedo'].includes(opts.coat)?'（完整毛色，花纹固定）':''}`;$('#patterns').innerHTML=G.availablePatterns(opts.coat).map(p=>`<button data-pattern="${p.id}" class="${p.id===opts.pattern?'selected':''}">${p.name}</button>`).join('');document.querySelectorAll('[data-pattern]').forEach(b=>b.onclick=()=>{opts.pattern=b.dataset.pattern;preview();});};preview();
 $('#cat-breed').onchange=e=>{opts.breedId=e.target.value;preview();};
 document.querySelectorAll('[data-coat]').forEach(b=>b.onclick=()=>{opts.coat=b.dataset.coat;document.querySelectorAll('[data-coat]').forEach(x=>x.classList.toggle('selected',x===b));preview();});
 for(const key of ['accessory'])document.querySelectorAll(`[data-${key}]`).forEach(b=>b.onclick=()=>{opts[key]=b.dataset[key];document.querySelectorAll(`[data-${key}]`).forEach(x=>x.classList.toggle('selected',x===b));preview();});
 $('#start').onclick=()=>{opts.name=G.safeName($('#cat-name').value);if(!opts.name){toast('先给你的第一只小猫起个名字吧。');$('#cat-name').focus();return;}state=G.newGame(opts);G.addVisitor(state,Date.now());save();$('#modal').close();render();CourtyardScene.setRoom('yard');toast('欢迎回家。门口已经有一位好奇的新朋友！');};
}
function render(){if(!state)return;$('#coins').textContent=Math.floor(state.coins);$('#resident-count').textContent=state.cats.filter(c=>c.status!=='visitor').length;$('#visitor-count').textContent=state.cats.filter(c=>c.status==='visitor').length;$('#collect').textContent=state.gifts?`🎁 小礼物 +${state.gifts}`:'🎁 小猫的礼物';$('#collect').disabled=!state.gifts;CourtyardScene.setState(state);if($('#collection').open)renderPanel();renderGuide();}
function openPanel(target){if(!state)return;tab=target;$('#collection-title').textContent=({cats:'小家人',shop:'布置你的家',memories:'有猫的回忆'})[tab];renderPanel();if(!$('#collection').open)$('#collection').showModal();}
function renderGuide(){let guide=$('#gentle-guide');if(!guide){guide=document.createElement('button');guide.id='gentle-guide';guide.className='gentle-guide';$('#game-stage').appendChild(guide);}const goal=G.nextGoal(state);guide.hidden=!goal;if(goal){guide.textContent='🐾 '+goal.text;guide.onclick=()=>goal.catId?detail(goal.catId):openPanel(goal.tab);}}
function appearance(c){return `${G.breedFor(c).name} · ${G.appearanceLabel(c)}`;}
function card(c){return `<button class="cat-card" data-cat="${escapeHtml(c.id)}"><span class="cat-avatar">${catSVG(c)}</span><span style="flex:1"><b>${escapeHtml(G.visitorDescription(c))}</b><span class="badge">${c.status==='visitor'?'尚未收养':c.status==='starter'?'初始小家人':'已定居'}</span><span class="cat-meta">${escapeHtml(appearance(c))}</span><span class="bar"><i style="width:${c.status==='visitor'?c.trust:Math.min(100,20+c.affection)}%"></i></span><span class="tiny">${c.status==='visitor'?`信任 ${c.trust}/100 · 留下后再起名`:`亲密度 ${c.affection} · 今天也喜欢你`}</span></span></button>`;}
function renderPanel(){document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));const panel=$('#panel');
 if(tab==='cats'){const residents=state.cats.filter(c=>c.status!=='visitor'),visitors=state.cats.filter(c=>c.status==='visitor');panel.innerHTML=`<div class="panel-title"><h2>家里的小家人</h2><small>${residents.length} 只猫咪</small></div><p class="subtext">每只猫都只有一个位置，它们有自己的小行程。${state.cats.length>12?'每处画面最多展示12只；点击「去看看它」会优先显示目标猫咪。':''}</p>${residents.map(c=>card(c)+`<div class="cat-location">📍 正在${escapeHtml(G.roomNames[c.location?.room]||'小院')} <button data-find="${escapeHtml(c.id)}">去看看它 →</button></div>`).join('')}<div class="section-label">门口的新朋友</div>${visitors.length?visitors.map(card).join(''):'<div class="empty"><span>🐾</span>门口暂时很安静。<br>布置好小院，让缘分慢慢来。</div>'}`;document.querySelectorAll('[data-find]').forEach(b=>b.onclick=()=>{CourtyardScene.findCat(b.dataset.find);$('#collection').close();});}
 else if(tab==='shop'){const effect=G.itemEffect(state),labels={food:'食物',box:'纸箱',warm:'温暖',plant:'花草',play:'玩具',climb:'攀爬'},visitorWeights=Object.entries(effect.visitorWeights).map(([tag,weight])=>`${labels[tag]||tag} ${weight}`).join(' · ')||'暂无';panel.innerHTML=`<div class="panel-title"><h2>给小院添点美好</h2><small>${state.placed.length} 件已摆放</small></div><p class="subtext">当前生效：喂食信任 +${effect.trustBonus} · 互动亲密 +${effect.affectionBonus} · 定居猫冷却 ${Math.round(60*effect.cooldownMultiplier)} 秒<br>来访偏好权重：${visitorWeights}</p><div class="shop-grid">${G.items.map(i=>`<div class="shop-item"><span>${i.emoji}</span><b>${i.name}</b><p>${i.desc}</p><p class="tiny">${escapeHtml(i.effectText)} · ${state.placed.includes(i.id)?'生效中':'摆放后生效'}</p><button data-buy="${i.id}" ${!state.owned.includes(i.id)&&state.coins<i.price?'disabled':''}>${state.owned.includes(i.id)?state.placed.includes(i.id)?'已摆放 · 收起':'摆进小院':`✧ ${i.price} 解锁`}</button></div>`).join('')}</div>`;
 document.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>{const id=b.dataset.buy;if(state.owned.includes(id)){state.placed=state.placed.includes(id)?state.placed.filter(x=>x!==id):[...state.placed,id];}else if(G.buy(state,id))toast('小院又多了一点可爱。');save();render();});}
 else panel.innerHTML=`<div class="panel-title"><h2>有猫的小日子</h2><small>${state.memories.length} 个瞬间</small></div><p class="subtext">那些小小的瞬间，也值得被珍藏。</p>${state.memories.map(m=>`<div class="memory"><time>${new Date(m.at).toLocaleString('zh-CN',{month:'long',day:'numeric',hour:'2-digit',minute:'2-digit'})}</time><p>${escapeHtml(m.text)}</p></div>`).join('')}`;
 bindCats();}
function bindCats(){document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>detail(b.dataset.cat));}
function detail(id){const c=state.cats.find(x=>x.id===id);if(!c)return;modal(`${top('和小猫待一会')}<div class="cat-detail"><div class="preview-cat">${catSVG(c)}</div><h3>${escapeHtml(G.visitorDescription(c))}</h3><p>${escapeHtml(appearance(c))}</p><p>${escapeHtml(c.personality)} · 喜欢${({food:'吃饭',box:'纸箱',warm:'暖暖的地方',plant:'花草',play:'小玩具',climb:'爬高高'})[c.favorite]||'晒太阳'}</p><div class="bar"><i style="width:${c.status==='visitor'?c.trust:Math.min(100,20+c.affection)}%"></i></div><p>${c.status==='visitor'?`信任 ${c.trust}/100 · 多陪伴几次，它就愿意留下。收养时再给它起名。`:`亲密度 ${c.affection} · 院子永远是它的家。`}</p></div><div class="action-row"><button class="secondary" id="pet">♡ 轻轻摸摸</button><button class="secondary" id="feed">🥣 添一碗饭</button></div>${c.status==='visitor'?`<button id="adopt" class="primary" ${c.trust<100?'disabled':''}>${c.trust<100?'再熟悉一点，就能邀请它留下':'邀请它成为小家人'}</button>`:'<button id="rename" class="primary">给它换个名字</button>'}<p class="tiny" style="text-align:center"><span id="interaction-status"></span> 随时回来，不用着急。</p>`);
 detailId=id;updateInteractionStatus();
 for(const a of ['pet','feed'])$('#'+a).onclick=()=>{const r=G.interact(state,id,a);save();render();if(r.ok){CourtyardScene.react(id,a);$('#modal').close();if($('#collection').open)$('#collection').close();}toast(r.text);};
 if($('#adopt'))$('#adopt').onclick=()=>nameDialog(c,true);if($('#rename'))$('#rename').onclick=()=>nameDialog(c,false);}
function updateInteractionStatus(){if(!detailId||!$('#modal').open||!$('#interaction-status'))return;const c=state?.cats.find(x=>x.id===detailId);if(!c)return;const cooldown=60000*(c.status==='visitor'?1:G.itemEffect(state).cooldownMultiplier),remaining=c.lastInteraction?Math.max(0,Math.ceil((cooldown-(Date.now()-c.lastInteraction))/1000)):0;for(const id of ['pet','feed'])if($('#'+id))$('#'+id).disabled=remaining>0;$('#interaction-status').textContent=remaining?`小猫正在回味，${remaining} 秒后可以再陪它。`:'小猫已经准备好和你待一会。';}
setInterval(updateInteractionStatus,1000);
function nameDialog(c,adopting){modal(`${top(adopting?'从今天起，这里就是家':'一个属于它的名字')}<div class="preview-cat">${catSVG(c)}</div><label class="field" for="new-name">你想叫它什么？</label><input id="new-name" class="name-input" maxlength="16" value="${escapeHtml(adopting?'':c.name)}" placeholder="这个名字，由你来起"><p class="tiny">${adopting?'名字确认后，它才正式成为家里的一员。':'给小家人一个新的昵称。'}</p><button id="confirm-name" class="primary">${adopting?'起名并收养 ♡':'记住这个名字'}</button>`);$('#confirm-name').onclick=()=>{const name=G.safeName($('#new-name').value);if(!name){toast('请给它起一个名字，不可以留空哦。');$('#new-name').focus();return;}if(adopting){if(!G.adopt(state,c.id,name)){toast('还不能收养这只小猫，请先多陪陪它。');return;}}else{c.name=name;G.memory(state,`给小猫取了一个新名字：「${name}」。`);}save();render();$('#modal').close();toast(adopting?`${name}留下来了，今后一起过日子。`:'名字已记在猫咪的小档案里。');};}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>openPanel(b.dataset.tab));
$('#close-collection').onclick=()=>$('#collection').close();
$('#call-cats').onclick=()=>{const count=CourtyardScene.call();toast(count?'轻轻摇摇零食袋，这个房间的小猫朝你走来了。':'这个房间暂时没有小猫。打开「小家人」可以找到它们。');};
document.addEventListener('catselect',e=>detail(e.detail));
document.addEventListener('artready',()=>{if(state){if($('#collection').open)renderPanel();document.querySelectorAll('[data-portrait]').forEach(img=>{const cat=state.cats.find(c=>c.id===img.dataset.portrait);const src=cat&&CourtyardScene.portrait(cat);if(src)img.src=src;});document.querySelectorAll('#modal .portrait-loading').forEach(el=>{const cat=state.cats.find(c=>c.id===detailId)||state.cats[0];if(CourtyardScene.portrait(cat))el.outerHTML=catSVG(cat);});}else if($('#preview'))$('#preview').innerHTML=catSVG({name:$('#cat-name')?.value,coat:document.querySelector('[data-coat].selected')?.dataset.coat||'orange',breedId:$('#cat-breed')?.value||'domestic',pattern:document.querySelector('[data-pattern].selected')?.dataset.pattern||'stripe',accessory:document.querySelector('[data-accessory].selected')?.dataset.accessory||'none'});});
document.addEventListener('arterror',()=>toast('小猫的插画还没加载成功，稍后刷新重试。存档仍会保留。'));
$('#collect').onclick=()=>{if(!state?.gifts)return;const n=state.gifts;state.coins+=n;state.gifts=0;G.memory(state,`猫咪们留下的小礼物，带来了 ${n} 枚猫爪印。`);save();render();toast(`收下小小心意，猫爪印 +${n}`);};
$('#save-info').onclick=()=>{modal(`${top('小院设置')}<div class="help"><p>点击猫咪可喂食、抚摸、命名。点击房门或底部地图探索家园。每只猫只在一个地方，定居猫会按自己的节奏换房间，来访猫留在小院。小家人列表会告诉你它们在哪里。</p><p>每分钟记一次陪伴。离线每半小时积累 3 枚猫爪印，最多结算 12 小时。</p><p>进度自动保存在当前浏览器。换设备或清除数据前，请导出存档。</p></div><div class="action-row"><button id="settings-export" class="secondary">导出存档</button><button id="settings-import" class="secondary">导入存档</button></div><button id="settings-restart" class="secondary" style="width:100%;margin-top:16px;color:#9a594c">重新开始</button>`);$('#settings-export').onclick=()=>$('#export-save').click();$('#settings-import').onclick=()=>$('#import-save').click();$('#settings-restart').onclick=()=>{modal(`${top('重新开始？')}<p class="help">这会清空当前存档中的猫咪、猫爪印、家具和回忆，且无法撤销。确认后，你将重新创建第一只小猫。</p><p class="help">如果想保留现在的小院，请先取消，再导出存档。</p><div class="action-row"><button id="cancel-restart" class="secondary">取消，保留小院</button><button id="confirm-restart" class="primary" style="background:#9a594c">清空存档并重开</button></div>`);$('#cancel-restart').onclick=()=>$('#save-info').click();$('#confirm-restart').onclick=()=>{try{localStorage.removeItem(KEY);}catch{toast('无法清空存档，当前进度已保留。请检查浏览器的存储权限。');return;}state=null;if($('#collection').open)$('#collection').close();if($('#gentle-guide'))$('#gentle-guide').hidden=true;onboarding();};};};
$('#export-save').onclick=()=>{if(!state)return;const url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='家-猫咪存档.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('存档已导出，请好好保管。');};
$('#import-save').onclick=()=>$('#import-file').click();$('#import-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>1000000)throw Error('存档过大');const imported=G.normalize(JSON.parse(await file.text()));modal(`${top('接回另一座小院')}<p class="help">这份存档里有 ${imported.cats.length} 只猫咪。导入会替换当前小院，建议先导出当前进度。</p><button id="confirm-import" class="primary">使用这份存档</button>`);$('#confirm-import').onclick=()=>{state=imported;G.settle(state);save();render();$('#modal').close();toast('小猫们都回来了。');};}catch{toast('这份存档无法读取，请选择导出的 JSON 存档。');}e.target.value='';};
function checkOffline(){if(!state)return;const result=G.settle(state);save();render();if(result.elapsed>30*60000&&(result.gifts||result.visits))modal(`${top('欢迎回来，猫咪想你了')}<div class="preview-cat">${catSVG(state.cats[0])}</div><p class="help">你不在的时候，小院也过得很好。<br>本次新增 <b>${result.gifts} 枚猫爪印</b><br>连同之前的小礼物，待领取共 <b>${state.gifts} 枚</b>${result.visits?'，还有一位新朋友在门口等你':''}。</p><button id="back-yard" class="primary">看看小院 ♡</button>`),$('#back-yard').onclick=()=>$('#modal').close();}
document.addEventListener('visibilitychange',()=>{if(document.hidden){if(state){state.lastSeen=Date.now();save();}}else checkOffline();});
window.addEventListener('pagehide',()=>{if(state){state.lastSeen=Date.now();save();}});
setInterval(()=>{if(state&&!document.hidden){const r=G.settle(state);save();render();if(r.visits)toast('门口有一位新朋友，去打声招呼吧。');}},30000);
try{const raw=localStorage.getItem(KEY);if(raw)state=G.normalize(JSON.parse(raw));}catch{toast('旧存档暂时无法读取，可以导入备份或重新领养。');}
if(state)checkOffline();else onboarding();
})();
