const test=require('node:test');const assert=require('node:assert/strict');const G=require('./game.js');
test('初始猫自定义与安全名字',()=>{const s=G.newGame({name:'  团子  ',coat:'gray',accessory:'bow'},100);assert.equal(s.cats[0].name,'团子');assert.equal(s.cats[0].coat,'gray');assert.equal(s.cats[0].status,'starter');});
test('奖励最多结算12小时，时间倒退没有负奖励',()=>{const s=G.newGame({},100);assert.equal(G.settle(s,100+24*3600000,()=>0).gifts,72);assert.equal(G.settle(s,0).gifts,0);});
test('来访猫信任与收养不重复',()=>{const s=G.newGame({},100);const c=G.addVisitor(s,100,()=>0);assert.equal(G.adopt(s,c.id,'团子'),false);for(let n=0;n<4;n++)assert.equal(G.interact(s,c.id,'feed',100000+n*60001).ok,true);assert.equal(c.trust,100);assert.equal(G.adopt(s,c.id,'新名字'),true);assert.equal(G.adopt(s,c.id,'重复'),false);assert.equal(c.name,'新名字');});
test('连续点击不会刷奖励',()=>{const s=G.newGame({},100);const c=s.cats[0];G.interact(s,c.id,'pet',100000);const coins=s.coins;assert.equal(G.interact(s,c.id,'feed',100001).ok,false);assert.equal(s.coins,coins);});
test('购买扣款且不会重复购买',()=>{const s=G.newGame();assert.equal(G.buy(s,'mat'),true);assert.equal(s.coins,20);assert.equal(G.buy(s,'mat'),false);assert.equal(G.buy(s,'house'),false);});
test('存档补齐与无效数据恢复',()=>{const s=G.newGame();s.owned=null;s.placed=['invalid'];s.memories=null;s.coins=-10;const n=G.normalize(s);assert.deepEqual(n.owned,['bowl','box']);assert.equal(n.coins,0);assert.deepEqual(n.placed,[]);assert.throws(()=>G.normalize({cats:[]}));});
test('来访数量上限与装饰偏好',()=>{const s=G.newGame({},0);s.placed=['box'];for(let n=1;n<=10;n++)G.settle(s,n*3600000,()=>0);assert.equal(s.cats.filter(c=>c.status==='visitor').length,3);assert.equal(s.cats[1].favorite,'box');});
test('频繁结算仍积累半小时礼物',()=>{const s=G.newGame({},0);for(let n=1;n<=60;n++)G.settle(s,n*30000,()=>0);assert.equal(s.gifts,3);});
test('前八只小猫有不同毛色，亲密度解锁回忆',()=>{const s=G.newGame({},0);for(let n=0;n<7;n++)G.addVisitor(s,0,()=>0);assert.equal(new Set(s.cats.map(c=>c.coat)).size,8);for(let n=1;n<=5;n++)G.interact(s,s.cats[0].id,'pet',n*60001);assert.ok(s.memories.some(m=>m.text.includes('解锁亲密回忆')));});
test('每只猫只属于一个房间，切换查询不会复制或改变位置',()=>{const s=G.newGame({},0),c=s.cats[0];G.moveCat(s,c.id,'bedroom',100,()=>.5);assert.equal(G.catsInRoom(s,'yard').length,0);assert.equal(G.catsInRoom(s,'bedroom').length,1);const before=JSON.stringify(c.location);for(const room of Object.keys(G.roomNames))G.catsInRoom(s,room);assert.equal(JSON.stringify(c.location),before);assert.equal(Object.keys(G.roomNames).flatMap(r=>G.catsInRoom(s,r)).length,s.cats.length);});
test('随机跨房间活动，来访猫仍留在院子',()=>{const s=G.newGame({},0);const v=G.addVisitor(s,0,()=>0);s.cats[0].location.nextMove=10;assert.equal(G.wanderLocations(s,20,()=>0),1);assert.equal(s.cats[0].location.room,'bedroom');assert.equal(v.location.room,'yard');assert.equal(G.moveCat(s,v.id,'kitchen'),false);});
test('旧存档迁移保留位置，剔除重复猫ID',()=>{const s=G.newGame({},0);G.moveCat(s,s.cats[0].id,'catroom',100,()=>.5);s.cats.push({...s.cats[0]});const n=G.normalize(JSON.parse(JSON.stringify(s)),200);assert.equal(n.cats.length,1);assert.equal(n.cats[0].location.room,'catroom');assert.equal(n.cats[0].location.x,.5);});

